Bug fix: Check for None in more places
We saw a crash on live and dev:

  File "/work/IATI-Publishing-Statistics/IATI-Stats/statsrunner/aggregate.py", line 117, in aggregate
    dict_sum_inplace(publisher_total, subtotal)
  File "/work/IATI-Publishing-Statistics/IATI-Stats/statsrunner/aggregate.py", line 29, in dict_sum_inplace
    dict_sum_inplace(d1[k], v)
  File "/work/IATI-Publishing-Statistics/IATI-Stats/statsrunner/aggregate.py", line 37, in dict_sum_inplace
    d1[k] += v
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'

Here is a local test you can run that crashes before this commit and doesn't afterwards:

import statsrunner.aggregate
import types
d1 = { "dogs": 67 }
d2 = { "dogs":None }
statsrunner.aggregate.dict_sum_inplace(d1,d2)

This PR is masking the root error; why is None suddenly coming through?
This however should let processing not crash and carry on